export const PASSWORD_RESET_PREFIX = 'password_reset:';
export const PASSWORD_RESET_TTL = 3600;

export const AUTH_CONSTANTS = {
  PASSWORD_RESET_PREFIX,
  PASSWORD_RESET_TTL,
  ACCESS_TOKEN_EXPIRY: '15m',
  REFRESH_TOKEN_EXPIRY: '7d',
  BCRYPT_ROUNDS: 12,
} as const;

export const VALIDATION_CONSTANTS = {
  PASSWORD_MIN_LENGTH: 8,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 30,
  DISPLAY_NAME_MIN_LENGTH: 2,
  DISPLAY_NAME_MAX_LENGTH: 100,
} as const;
